# Generated by Django 5.2.3 on 2025-07-03 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.TextField(max_length=250)),
                ('mood', models.CharField(blank=True, choices=[('anxious', 'Anxious'), ('calm', 'Calm'), ('cheerful', 'Cheerful'), ('depressing', 'Depressing'), ('eerie', 'Eerie'), ('festive', 'Festive'), ('foreboding', 'Foreboding'), ('frightening', 'Frightening'), ('frustrated', 'Frustrated'), ('gloomy', 'Gloomy'), ('hopeless', 'Hopeless'), ('humorous', 'Humorous'), ('idyllic', 'Idyllic'), ('joyful', 'Joyful'), ('light-hearted', 'Light-hearted'), ('lonely', 'Lonely'), ('mlancholic', 'Melancholic'), ('mysterious', 'Mysterious'), ('ominous', 'Ominous'), ('optimistic', 'Optimistic'), ('panicked', 'Panicked'), ('peaceful', 'Peaceful'), ('pensive', 'Pensive'), ('pessimistic', 'Pessimistic'), ('reflective', 'Reflective'), ('romantic', 'Romantic'), ('sad', 'Sad'), ('sentimental', 'Sentimental'), ('stressed', 'Stressed'), ('suspenseful', 'Suspenseful'), ('tense', 'Tense'), ('uneasy', 'Uneasy'), ('uplifting', 'Uplifting'), ('whimsical', 'Whimsical')], max_length=20, null=True)),
                ('chapter', models.CharField(blank=True, max_length=100, null=True)),
                ('page', models.IntegerField(blank=True, null=True)),
                ('date_added', models.DateField(auto_now_add=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.book')),
            ],
        ),
    ]
