# Generated by Django 5.2.3 on 2025-07-05 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_bookshelf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookshelf',
            name='color',
            field=models.CharField(choices=[('aqua', 'Aqua'), ('blue', 'Blue'), ('fuchsia', 'Fuchsia'), ('gray', 'Gray'), ('green', 'Green'), ('lime', 'Lime'), ('maroon', 'Maroon'), ('navy', 'Navy'), ('olive', 'Olive'), ('purple', 'Purple'), ('red', 'Red'), ('silver', 'Silver'), ('teal', 'Teal'), ('yellow', 'Yellow'), ('fornflowerblue', 'CornflowerBlue'), ('indianred', 'IndianRed'), ('darkcyan', 'DarkCyan'), ('lightseagreen', 'LightSeaGreen'), ('mediumpurple', 'MediumPurple'), ('darkslategray', 'DarkSlateGray')], max_length=20),
        ),
    ]
