# Generated by Django 5.2.3 on 2025-07-02 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('author', models.CharField(blank=True, max_length=250, null=True)),
                ('description', models.TextField(blank=True, max_length=250)),
                ('thumbnail', models.URLField(blank=True, null=True)),
                ('status', models.CharField(choices=[('tbr', 'TBR'), ('reading', 'Reading'), ('read', 'Read'), ('paused', 'Paused'), ('dnf', 'DNF')], default='tbr', max_length=10)),
                ('format', models.CharField(blank=True, choices=[('audio', 'Audiobook'), ('ebook', 'eBook'), ('physical', 'Physical Book')], max_length=10, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('finish_date', models.DateField(blank=True, null=True)),
                ('genre', models.CharField(choices=[('biography', 'Biography'), ('classic', 'Classic'), ('contemporary_fiction', 'Contemporary Fiction'), ('dark_academia', 'Dark Academia'), ('fantasy', 'Fantasy'), ('historical_fiction', 'Historical Fiction'), ('history', 'History'), ('horror', 'Horror'), ('literary_fiction', 'Literary Fiction'), ('memoir', 'Memoir'), ('mystery', 'Mystery'), ('nonfiction', 'Nonfiction'), ('play', 'Play'), ('poetry', 'Poetry'), ('retelling', 'Retelling'), ('romance', 'Romance'), ('romantasy', 'Romantasy'), ('science_fiction', 'Science Fiction'), ('thriller', 'Thriller'), ('young_adult', 'Young Adult')], max_length=20)),
                ('publication_year', models.IntegerField(blank=True, null=True)),
                ('total_pages', models.IntegerField(blank=True, null=True)),
                ('total_time', models.DurationField(blank=True, null=True)),
                ('re_read', models.BooleanField(default=False)),
                ('date_added', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
