# Generated by Django 5.2.3 on 2025-07-03 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_journal'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='journal',
            options={'ordering': ['date_added']},
        ),
    ]
