# Generated by Django 5.2.3 on 2025-07-04 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_book_date_added_alter_journal_date_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
