# Generated by Django 5.2.3 on 2025-07-05 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_alter_bookshelf_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='bookshelf',
            field=models.ManyToManyField(to='main_app.bookshelf'),
        ),
    ]
