# Generated by Django 5.2.3 on 2025-07-07 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_book_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.CharField(choices=[('biography', 'Biography'), ('classic', 'Classic'), ('contemporary_fiction', 'Contemporary Fiction'), ('dark_academia', 'Dark Academia'), ('fantasy', 'Fantasy'), ('historical_fiction', 'Historical Fiction'), ('history', 'History'), ('horror', 'Horror'), ('literary_fiction', 'Literary Fiction'), ('memoir', 'Memoir'), ('mystery', 'Mystery'), ('nonfiction', 'Nonfiction'), ('play', 'Play'), ('poetry', 'Poetry'), ('retelling', 'Retelling'), ('romance', 'Romance'), ('romantasy', 'Romantasy'), ('science_fiction', 'Science Fiction'), ('thriller', 'Thriller'), ('young_adult', 'Young Adult')], default='fantasy', max_length=20),
        ),
    ]
