# Generated by Django 5.2.3 on 2025-07-08 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_remove_book_bookshelf_delete_bookshelf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='user',
        ),
    ]
