# Generated by Django 5.2.3 on 2025-07-08 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_remove_book_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='description',
        ),
        migrations.RemoveField(
            model_name='book',
            name='finish_date',
        ),
        migrations.RemoveField(
            model_name='book',
            name='publication_year',
        ),
        migrations.RemoveField(
            model_name='book',
            name='re_read',
        ),
        migrations.RemoveField(
            model_name='book',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='book',
            name='total_pages',
        ),
        migrations.RemoveField(
            model_name='book',
            name='total_time',
        ),
    ]
