# Generated by Django 5.2.3 on 2025-07-08 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0014_remove_book_description_remove_book_finish_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='format',
        ),
        migrations.RemoveField(
            model_name='book',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='book',
            name='status',
        ),
        migrations.RemoveField(
            model_name='book',
            name='thumbnail',
        ),
    ]
